apiVersion: v1
kind: Namespace
metadata:
  name: birthdays

---
apiVersion: v1
kind: Secret
metadata:
  name: birthdays-credentials
  namespace: birthdays
type: Opaque
data:
  db-username: revolut
  db-password: YWJzb2x1dGUK