steps:

- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'project_id=$PROJECT_ID', '-t', 'gcr.io/$PROJECT_ID/${_APP_}:${_ENV_}-$BRANCH_NAME-$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/${_APP_}:${_ENV_}-latest', '.']

- id: Run Migrations Job
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '.kubernetes/migrations-job.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=eu-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_APP_}-${_REGION_}-cluster'
  waitFor:
  - 'Run Migrations Job'

- id: Run Tests Job
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '.kubernetes/tests-job.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=eu-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_APP_}-${_REGION_}-cluster'
  waitFor:
  - 'Build Docker Image'

- id: Rollout Depployment to GKE
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - ${_APP_}-deployment
  - ${_APP_}-container=gcr.io/$PROJECT_ID/${_APP_}:${_ENV_}-$BRANCH_NAME-$SHORT_SHA
  - --record=true
  - --namespace=${_APP_}
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=eu-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_APP_}-${_REGION_}-cluster'
  waitFor:
  - 'Run Tests Job'

substitutions:
    _ENV_: production
    _APP_: birthdays
    _REGION_: eu

images:
- 'gcr.io/$PROJECT_ID/${_APP_}:${_ENV_}-$BRANCH_NAME-$SHORT_SHA'
- 'gcr.io/$PROJECT_ID/${_APP_}:${_ENV_}-latest'